version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forewarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    env_file:
     - backend/.env-prod
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    command: [--auth] # enables authentication
    volumes: ['/root/runmarc-mongodb:/data/db']
    ports:
      - "27017:27017" # specify port fordwarding
